# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180202_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.DateField(),
        ),
    ]
