# Generated by Django 2.0.2 on 2018-02-15 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180210_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepicture',
            old_name='profile',
            new_name='account',
        ),
    ]
