# Generated by Django 2.0.2 on 2018-03-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180215_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
