# Generated by Django 2.0.2 on 2018-03-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180319_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
