# Generated by Django 2.0.2 on 2018-03-30 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180326_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_pos', models.IntegerField(default=0)),
                ('o_neg', models.IntegerField(default=0)),
                ('a_pos', models.IntegerField(default=0)),
                ('a_neg', models.IntegerField(default=0)),
                ('b_pos', models.IntegerField(default=0)),
                ('b_neg', models.IntegerField(default=0)),
                ('ab_pos', models.IntegerField(default=0)),
                ('ab_neg', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
