# Generated by Django 2.0.2 on 2018-03-30 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bloodcollection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodCollection',
            new_name='Blood',
        ),
    ]
