# Generated by Django 2.0.2 on 2018-03-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180331_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='street_number',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='request',
            name='location',
        ),
        migrations.AddField(
            model_name='request',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='post_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='road',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
