# Generated by Django 2.0.3 on 2018-04-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
