# Generated by Django 2.0.3 on 2018-04-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180423_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='gender',
        ),
    ]
